using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.EventSystems;

public class MouseScript : MiniGame
{
    public ParticleSystem ps;
    public IEnumerator Win()
    {
        
        ps.Play();
        yield return new WaitForSeconds(0.3f);
        OnGameOver(true);
    }
}
//XXXXXXXXXXXXXXXXXXXXXXXXXX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XOOVVOOOOOOOOOOOOOOOOOOOOX
//XOOVVOOOOOOOOOOOOOOOOOOOOX
//XOOVVOOOOOOOOOOOOOOOOOOOOX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XOOOOOOOOOOOOOOOOOOOSSOOOX
//XOOOOOOOOOOOOOOOOOOOSSOOOX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XOOOOOOOOOOOOOOOOOOOOOOOOX
//XXXXXXXXXXXXXXXXXXXXXXXXXX

//---